In [1]:
import pandas as pd
import numpy as np

In [2]:
best_seasons = pd.read_csv("best_seasons.csv")
best_seasons = best_seasons.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)
best_seasons

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,usg_pct,ts_pct,ast_pct,season
0,A.C. Green,DAL,34,81.0,225.0,Oregon State,USA,1985.0,1,23,82,7.3,8.1,1.5,-7.2,0.118,0.496,0.074,1997-98
1,A.J. Bramlett,CLE,23,82.0,227.0,Arizona,USA,1999.0,2,39,8,1.0,2.8,0.0,-32.6,0.146,0.190,0.000,1999-00
2,A.J. Guyton,CHI,23,73.0,180.0,Indiana,USA,2000.0,2,32,33,6.0,1.1,1.9,-12.4,0.169,0.495,0.198,2000-01
3,A.J. Lawson,DAL,22,78.0,179.0,South Carolina,Canada,NaN,Undrafted,Undrafted,15,3.7,1.4,0.1,-20.1,0.189,0.589,0.032,2022-23
4,AJ Green,MIL,23,77.0,190.0,Northern Iowa,USA,NaN,Undrafted,Undrafted,35,4.4,1.3,0.6,-4.9,0.159,0.607,0.092,2022-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,Zion Williamson,NOP,20,79.0,284.0,Duke,USA,2019.0,1,1,61,27.0,7.2,3.7,2.1,0.287,0.649,0.188,2020-21
2547,Zoran Dragic,MIA,26,77.0,200.0,NaN,Slovenia,NaN,Undrafted,Undrafted,16,1.8,0.5,0.3,-15.3,0.217,0.435,0.116,2014-15
2548,Zoran Planinic,NJN,22,79.0,200.0,NaN,Croatia,2003.0,1,22,43,5.0,1.6,1.0,-4.8,0.227,0.534,0.185,2004-05
2549,Zydrunas Ilgauskas,CLE,28,87.0,260.0,NaN,Lithuania,1996.0,1,20,81,17.2,7.5,1.6,-7.9,0.279,0.516,0.101,2002-03
2550,Zylan Cheatham,NOP,24,77.0,220.0,Arizona State,USA,NaN,Undrafted,Undrafted,4,3.0,2.3,0.8,-23.9,0.103,0.667,0.094,2019-20

In [3]:
draft_combine = pd.read_csv('draft_combine_data.csv')
draft_combine = draft_combine.drop('Unnamed: 0', axis=1)
draft_combine

,YEAR,PLAYER,POS,HGT,WGT,BMI,BF,WNGSPN,STNDRCH,HANDL,HANDW,STNDVERT,LPVERT,LANE,SHUTTLE,SPRINT
0,2024,Michael Ajayi,SF,77.80,227.8,26.49,NaN,84.80,106.5,9.5,9.8,27.0,34.5,12.00,3.17,3.21
1,2024,Melvin Ajinca,SF,79.30,213.8,23.93,NaN,79.50,106.5,8.5,9.8,26.5,31.0,12.00,3.00,3.38
2,2024,Trey Alexander,SG,75.30,187,23.22,NaN,82.50,101.5,9.0,10.0,27.0,32.0,11.00,3.00,3.00
3,2024,Izan Almansa,C,81.30,219.6,23.39,NaN,85.00,110.0,9.0,9.0,28.0,35.0,11.00,3.00,3.00
4,2024,Reece Beekman,PG,73.30,196.4,25.73,NaN,78.50,100.0,9.0,9.0,30.0,37.0,11.00,3.00,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1605,2000,Mike Smith,SF,78.50,198,22.59,NaN,80.50,103.0,NaN,NaN,33.0,21.0,11.32,NaN,3.22
1606,2000,Jarrett Stephens,PF,77.25,258,30.39,NaN,81.25,103.0,NaN,NaN,27.0,29.0,11.98,NaN,3.46
1607,2000,Bootsy Thornton,SG,75.50,194.5,23.99,NaN,78.50,101.5,NaN,NaN,26.5,31.0,12.08,NaN,3.33
1608,2000,Jaquay Walls,PG,73.25,165.5,21.68,NaN,74.50,96.5,NaN,NaN,28.5,35.5,10.75,NaN,3.23
1609,2000,Jameel Watkins,PF-C,81.50,244.5,25.88,NaN,90.00,110.0,NaN,NaN,28.0,30.5,12.38,NaN,3.45

In [4]:
merged_df = pd.merge(best_seasons, draft_combine, left_on='player_name', right_on='PLAYER')
merged_df = merged_df.drop(['team_abbreviation', 'college', 'country', 'HANDL', 'HANDW', 'PLAYER', 'YEAR', 'HGT', 'WGT'], axis=1)
merged_df

,player_name,age,player_height,player_weight,draft_year,draft_round,draft_number,gp,pts,reb,...,POS,BMI,BF,WNGSPN,STNDRCH,STNDVERT,LPVERT,LANE,SHUTTLE,SPRINT
0,A.J. Guyton,23,73.0,180.0,2000.0,2,32,33,6.0,1.1,...,PG-SG,23.24,NaN,75.75,97.5,33.0,37.5,10.55,NaN,3.22
1,Aaron Brooks,25,72.0,161.0,2007.0,1,26,82,19.6,2.6,...,PG,23.10,0.0270,76.00,94.0,32.5,39.5,10.57,NaN,3.20
2,Aaron Gordon,22,81.0,220.0,2014.0,1,4,58,17.6,7.9,...,PF,24.48,0.0505,83.75,105.0,32.5,39.0,10.81,2.76,3.27
3,Aaron Gray,23,84.0,270.0,2007.0,2,49,61,4.3,2.8,...,C,27.00,0.1080,87.25,108.5,27.0,32.5,12.07,NaN,3.70
4,Aaron Harrison,23,78.0,210.0,NaN,Undrafted,Undrafted,9,6.7,2.7,...,SG,25.13,0.0600,80.25,100.5,28.5,34.5,NaN,NaN,3.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Zach Norvell Jr.,22,77.0,205.0,2019.0,Undrafted,Undrafted,5,2.0,1.2,...,SG,24.79,0.0750,78.00,101.0,24.0,30.0,11.60,3.34,3.43
980,Zeke Nnaji,21,81.0,240.0,2020.0,1,22,41,6.6,3.6,...,PF-C,26.28,0.0590,86.00,105.5,33.0,38.0,10.94,2.72,3.20
981,Zhaire Smith,20,76.0,199.0,2018.0,1,16,6,6.7,2.2,...,SF-SG,24.99,0.0605,81.75,100.0,33.0,41.5,11.02,3.15,3.05
982,Zhou Qi,23,85.0,210.0,2016.0,2,43,1,2.0,0.0,...,PF-C,21.11,0.0485,91.75,112.5,31.5,32.0,11.27,2.90,3.46
983,Ziaire Williams,20,81.0,185.0,2021.0,1,10,62,8.1,2.1,...,SF,20.57,0.0440,82.25,106.5,34.0,39.5,10.69,3.04,3.12

In [5]:
merged_df.columns

Index(['player_name', 'age', 'player_height', 'player_weight', 'draft_year',
       'draft_round', 'draft_number', 'gp', 'pts', 'reb', 'ast', 'net_rating',
       'usg_pct', 'ts_pct', 'ast_pct', 'season', 'POS', 'BMI', 'BF', 'WNGSPN',
       'STNDRCH', 'STNDVERT', 'LPVERT', 'LANE', 'SHUTTLE', 'SPRINT'],
      dtype='object')

In [6]:
merged_df.info

<bound method DataFrame.info of           player_name  age  player_height  player_weight  draft_year  \
0         A.J. Guyton   23           73.0          180.0      2000.0
1        Aaron Brooks   25           72.0          161.0      2007.0
2        Aaron Gordon   22           81.0          220.0      2014.0
3          Aaron Gray   23           84.0          270.0      2007.0
4      Aaron Harrison   23           78.0          210.0         NaN
..                ...  ...            ...            ...         ...
979  Zach Norvell Jr.   22           77.0          205.0      2019.0
980        Zeke Nnaji   21           81.0          240.0      2020.0
981      Zhaire Smith   20           76.0          199.0      2018.0
982           Zhou Qi   23           85.0          210.0      2016.0
983   Ziaire Williams   20           81.0          185.0      2021.0

    draft_round draft_number  gp   pts  reb  ...    POS    BMI      BF  \
0             2           32  33   6.0  1.1  ...  PG-SG  23.24     NaN
1             1           26  82  19.6  2.6  ...     PG  23.10  0.0270
2             1            4  58  17.6  7.9  ...     PF  24.48  0.0505
3             2           49  61   4.3  2.8  ...      C  27.00  0.1080
4     Undrafted    Undrafted   9   6.7  2.7  ...     SG  25.13  0.0600
..          ...          ...  ..   ...  ...  ...    ...    ...     ...
979   Undrafted    Undrafted   5   2.0  1.2  ...     SG  24.79  0.0750
980           1           22  41   6.6  3.6  ...   PF-C  26.28  0.0590
981           1           16   6   6.7  2.2  ...  SF-SG  24.99  0.0605
982           2           43   1   2.0  0.0  ...   PF-C  21.11  0.0485
983           1           10  62   8.1  2.1  ...     SF  20.57  0.0440

     WNGSPN  STNDRCH STNDVERT LPVERT   LANE  SHUTTLE  SPRINT
0     75.75     97.5     33.0   37.5  10.55      NaN    3.22
1     76.00     94.0     32.5   39.5  10.57      NaN    3.20
2     83.75    105.0     32.5   39.0  10.81     2.76    3.27
3     87.25    108.5     27.0   32.5  12.07      NaN    3.70
4     80.25    100.5     28.5   34.5    NaN      NaN    3.27
..      ...      ...      ...    ...    ...      ...     ...
979   78.00    101.0     24.0   30.0  11.60     3.34    3.43
980   86.00    105.5     33.0   38.0  10.94     2.72    3.20
981   81.75    100.0     33.0   41.5  11.02     3.15    3.05
982   91.75    112.5     31.5   32.0  11.27     2.90    3.46
983   82.25    106.5     34.0   39.5  10.69     3.04    3.12

[984 rows x 26 columns]>

In [18]:
merged_df.dtypes

player_name       object
age                int64
player_height    float64
player_weight    float64
draft_year       float64
draft_round       object
draft_number      object
gp                 int64
pts              float64
reb              float64
ast              float64
net_rating       float64
usg_pct          float64
ts_pct           float64
ast_pct          float64
season            object
POS               object
BMI              float64
BF               float64
WNGSPN           float64
STNDRCH          float64
STNDVERT         float64
LPVERT           float64
LANE             float64
SHUTTLE          float64
SPRINT           float64
dtype: object

In [7]:
test = merged_df[merged_df['player_name'] == 'James Harden']
test

,player_name,age,player_height,player_weight,draft_year,draft_round,draft_number,gp,pts,reb,...,POS,BMI,BF,WNGSPN,STNDRCH,STNDVERT,LPVERT,LANE,SHUTTLE,SPRINT
405,James Harden,29,77.0,220.0,2009.0,1,3,78,36.1,6.6,...,SG,27.02,0.101,82.75,103.5,31.5,37.0,11.1,NaN,3.13